language: java
jdk:
- oraclejdk8
sudo: false
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn package
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kevin.vanhoutte@ordina.be
  password:
    secure: ANvllnvyip5mEvGmCiynG0c3+gzUzYGbwfo1XOQDh0IlnvBEy5y2/I5V+mkTf61sXarzCYVCbLHAzd6YBrPjpjyK7L+h8t+MBUWfMiIK+3arywvR2sjuUdYyCWIM+0JMKGZnmifOaDPI9ndVnTLvpqGSVZ9tM80pb/m8eVTnc5do+eVLICovuXaVNk9IrJPGlYN+VuKCUaK3Ky+NIHM1ndyVZ8F7eMLgxnKhjA2ugWxQKvi3HcDLux7fendR+tV/W3C90LjW5sgi7oU1w23gCtpILKvzgs9eMZ5E1DRM3IYs5GY2lkpIEW9C31D2W3JWNLiF9NJQkSuNU3eL0o4iy/R91aV2CWxPfvZbSh8DeS78xuCNkFuOD65aImyv6Nxpp5Oh5c53T1fZ+aCcTJBzZ7SqlejUMrCqQ+EfSXZXJmgrExd3im6Cd0mUUEzBkuyNtceAA2koBxGSWDwdXiqwlCH0MRCLxTdH3JFDsPmtbecAIStfXppcqO7rVn8UcQ0Xy9gUyFkU1pSsXvF6AOCxMUNwWwHQD1jExkc0UZCiRbRcqP5UlYDSI1dKWwU+IoSF9+gT6VvqS56YT8tSLe3Qkvap3zJOk/ZN5uKko3K9SfJtGyBTc3FwC+Yd1nh+qJ21Yo7ZRooYw895nqezCDSex/aqOKQiUsExscO4Fzmc2Iw=
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: Ordineo/auth-server
    branch: master
notifications:
  slack:
    secure: Xc9GUY0Cs/8+KqZCoX/3sh5j2+i3l/JAESeGAFOs2ywFjpngi2D5moE+kJvMN6k56z79LAL9T9E1AzTdFy2AuOsDjGisw+sMzphoM899vosaz/E8byqwGsG25S1i/QlQBJQdkXuf1ZyRF+oLz5HBIIdfQqfLbLnc5v2t/kMdXcwdkNk9plkwcEV1ju6F2ZUKEK+Zh7tJzemwv0+l51pJMuNurI+AEKZN7uLJBU++64NLxl4aoo15fj7wts6AJlVjxjQ4hsuiFGGz0DvkefiOp27Nhq8gioj15QF9ayTcqZ6YM4sD0JHDGuNuoTh+H4/pPZjCnrGlczqx+xtS4dFqY7utrhB7L+D4O6ol9UJz+RvTvCvrlB2jWB0GvaLJv5Zw8SaROAOrd8xUn5xCFDD6wArE8QvzzaXpttW/BPWQUPkNCBhYqbnxYImzgA+xg57IwP+DtpgOoJv2DtgoAixcdETueTGlUMFunVixCyw+0nh5pSv6YGy61XQb2SX5j//eXbU8rAe68ccLD4X1AtzcCx/rCSAZcwVM5GsYUZerCmimGC04S0y16L/WXZUSNcPeiZzGXumxhJZYGkbAk3hS5pqRUzG1XF1O5BrnvgFZcRbfwoPtmZ/dH5nVRiQ+BYvoHRSUKp16lmEz44z/zv5uOtnG1cOCqBMArNQgKqtDeiQ=