server:
  port: ${PORT:9999}
  contextPath: /uaa
spring:
  redis:
    host: pub-redis-15392.us-east-1-4.4.ec2.garantiadata.com
    database: 0
    port: 15392
security:
#  oauth2:
#      client:
#        clientId: acme
#        clientSecret: acmesecret
#        authorized-grant-types: authorization_code,refresh_token,password
#        scope: openid
#        auto-approve-scopes: '.*'
  user:
    password: password
  sessions: NEVER
logging:
  level:
    org:
      springframework:
        security: DEBUG

